<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'product_category_id' => 4,
                'name' => 'Manfinity EMRG Nam',
                'description' => '',
                'content' => '',
                'price' => 617,
                'amount' => 20,
                'featured' => "1",
                'image' => "aokhoac_2.jpg",
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 4,
                'name' => 'Manfinity Homme Nam',
                'description' => '',
                'content' => '',
                'price' => 731,
                'amount' => 20,
                'featured' => "1",
                'image' => "homme_1.jpg",
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 4,
                'name' => 'Manfinity Homme Nam Đen',
                'description' => '',
                'content' => '',
                'price' => 607,
                'amount' => 20,
                'featured' => "1",
                'image' => "homme_den_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 2,
                'name' => 'WM Ống tay áo sơ mi',
                'description' => '',
                'content' => '',
                'price' => 385,
                'amount' => 20,
                'featured' => "1",
                'image' => "dazy_nu_1.jpg",
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'WM Hoa văn kẻ sọc',
                'description' => '',
                'content' => '',
                'price' => 326,
                'amount' => 20,
                'featured' => "1",
                'image' => "thoitrangnu_2.jpg",
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'WM Áo sơ mi',
                'description' => '',
                'content' => '',
                'price' => 318,
                'amount' => 20,
                'featured' => "1",
                'image' => "dazy_aosomi_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 2,
                'name' => 'WM Tay Raglan',
                'description' => '',
                'content' => '',
                'price' => 198,
                'amount' => 20,
                'featured' => "1",
                'image' => "dazy_thun_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 1,
                'name' => 'Manfinity Nam Áo thun',
                'description' => '',
                'content' => '',
                'price' => 221,
                'amount' => 20,
                'featured' => "1",
                'image' => "thoitrangnam_1.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Manfinity Hypemode Nam',
                'description' => '',
                'content' => '',
                'price' => 450,
                'amount' => 20,
                'featured' => "2",
                'image' => "homme_hypermode_1.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Manfinity Chillmode Áo sơ mi Nam',
                'description' => '',
                'content' => '',
                'price' => 287,
                'amount' => 20,
                'featured' => "2",
                'image' => "homme_chillmode_1.jpg",
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 5,
                'name' => 'Manfinity EMRG Nam Rách Frayed',
                'description' => '',
                'content' => '',
                'price' => 493,
                'amount' => 20,
                'featured' => "2",
                'image' => "jeans_2.jpg",
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 5,
                'name' => 'Manfinity Quần legging',
                'description' => '',
                'content' => '',
                'price' => 399,
                'amount' => 20,
                'featured' => "2",
                'image' => "legging_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 4,
                'name' => 'Manfinity EMRG Nam Áo khoác',
                'description' => '',
                'content' => '',
                'price' => 692,
                'amount' => 20,
                'featured' => "2",
                'image' => "emrg_aokhoac_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 4,
                'name' => 'Manfinity EMRG Nam Áo khoác có đồ hoạ',
                'description' => '',
                'content' => '',
                'price' => 627,
                'amount' => 20,
                'featured' => "2",
                'image' => "emrg_aokhoac_2.jpg",
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'WM Off Shoulder Áo phông Crop',
                'description' => '',
                'content' => '',
                'price' => 173,
                'amount' => 20,
                'featured' => "2",
                'image' => "wm_offshoulder_1.jpg",
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'WM Vai lạnh Áo thun',
                'description' => '',
                'content' => '',
                'price' => 134,
                'amount' => 20,
                'featured' => "2",
                'image' => "wm_vailanh_1.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => 'WM Váy Hồng',
                'description' => '',
                'content' => '',
                'price' => 179,
                'amount' => 20,
                'featured' => "0",
                'image' => "thoitrangnu_1.png",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => 'WM Váy Đen',
                'description' => '',
                'content' => '',
                'price' => 219,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-4.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 3,
                'name' => 'Áo Sơ Mi Trẻ Em',
                'description' => '',
                'content' => '',
                'price' => 159,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-8.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 3,
                'name' => 'Áo Khoác Trẻ Em',
                'description' => '',
                'content' => '',
                'price' => 249,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-2.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 3,
                'name' => 'Áo Khoác thun Trẻ Em',
                'description' => '',
                'content' => '',
                'price' => 129,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-5.jpg",
            ],
        ]);
    }
}