<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'product_category_id' => 4,
                'name' => 'Manfinity EMRG Nam',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 617.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "aokhoac_2.jpg",
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 4,
                'name' => 'Manfinity Homme Nam',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 731.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "homme_1.jpg",
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 4,
                'name' => 'Manfinity Homme Nam Đen',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 607.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "homme_den_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 2,
                'name' => 'WM Ống tay áo sơ mi',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 385.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "dazy_nu_1.jpg",
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'WM Hoa văn kẻ sọc',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 326.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "thoitrangnu_2.jpg",
            ],
            [
                'brand_id' => 5,
                'product_category_id' => 2,
                'name' => 'WM Áo sơ mi',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 318.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "dazy_aosomi_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 2,
                'name' => 'WM Tay Raglan',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 198.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "dazy_thun_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 1,
                'name' => 'Manfinity Nam Áo thun',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 221.000,
                'amount' => 20,
                'featured' => "1",
                'image' => "thoitrangnam_1.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Manfinity Hypemode Nam',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 450.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "homme_hypermode_1.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 1,
                'name' => 'Manfinity Chillmode Áo sơ mi Nam',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 287.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "homme_chillmode_1.jpg",
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 5,
                'name' => 'Manfinity EMRG Nam Rách Frayed',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 493.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "jeans_2.jpg",
            ],
            [
                'brand_id' => 3,
                'product_category_id' => 5,
                'name' => 'Manfinity Quần legging',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 399.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "legging_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 4,
                'name' => 'Manfinity EMRG Nam Áo khoác',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 692.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "emrg_aokhoac_1.jpg",
            ],
            [
                'brand_id' => 4,
                'product_category_id' => 4,
                'name' => 'Manfinity EMRG Nam Áo khoác có đồ hoạ',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 627.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "emrg_aokhoac_2.jpg",
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'WM Off Shoulder Áo phông Crop',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 173.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "wm_offshoulder_1.jpg",
            ],
            [
                'brand_id' => 2,
                'product_category_id' => 2,
                'name' => 'WM Vai lạnh Áo thun',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 134.000,
                'amount' => 20,
                'featured' => "2",
                'image' => "wm_vailanh_1.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => 'WM Váy Hồng',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 179.000,
                'amount' => 20,
                'featured' => "0",
                'image' => "thoitrangnu_1.png",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 2,
                'name' => 'WM Váy Đen',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 219.000,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-4.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 3,
                'name' => 'Áo Sơ Mi Trẻ Em',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 159.000,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-8.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 3,
                'name' => 'Áo Khoác Trẻ Em',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 249.000,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-2.jpg",
            ],
            [
                'brand_id' => 1,
                'product_category_id' => 3,
                'name' => 'Áo Khoác thun Trẻ Em',
                'description' => 'Lorem ipsum dolor sit amet, consectetur ing elit, sed do eiusmod tempor sum dolor sit amet, consectetur adipisicing elit, sed do mod tempor',
                'content' => '',
                'price' => 129.000,
                'amount' => 20,
                'featured' => "0",
                'image' => "product-5.jpg",
            ],
        ]);
    }
}